import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    // Alternate build outputs (NEXT_DIST_DIR); generated, like .next itself.
    ".next-*/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // The processor's bundled worker output (G-034): generated by `npm run build:processor`, git-ignored, and
    // megabytes of third-party code that lint has nothing useful to say about.
    "dist/**",
  ]),
  // `lib/` is the framework-free layer: pure modules the unit tests exercise without rendering anything, and the
  // same code the processor runs server-side where there is no React at all (STANDARDS.md -> Software). Two hooks
  // had drifted in before G-067 M6; this keeps the boundary a rule rather than a tendency.
  {
    files: ["lib/**/*.ts", "lib/**/*.tsx"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            { name: "react", message: "lib/ stays framework-free: put the hook in app/hooks/ and keep the logic here as a pure module." },
            {
              name: "react-dom",
              message: "lib/ stays framework-free: put the hook in app/hooks/ and keep the logic here as a pure module.",
            },
          ],
        },
      ],
    },
  },
  // A tool is one module (G-092, D284): it touches the editor only through the API it is handed, so it may not reach for
  // the workspace, the registry or the shell. That it imports no other tool is checked by tests/unit/tool-registry.spec.ts,
  // which knows the modules' names.
  {
    files: ["app/tools/*.ts", "app/tools/*.tsx"],
    ignores: ["app/tools/registry.ts", "app/tools/use-tools.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/workspace", "./registry", "./use-tools"],
              message:
                "A tool module uses only the EditorApi it is given (app/tools/types.ts): not the workspace, the registry or the shell.",
            },
          ],
        },
      ],
    },
  },
]);

export default eslintConfig;
