// G-093: the command table in code is the one the documents state.
//   1. The table has nothing wrong with it (one id one command, real keys, no letter or digit claimed twice).
//   2. The keys in the design brief's "Keyboard shortcuts" table (docs/design-brief/04-editing.md) are exactly the table's keys.
//   3. The command table in docs/interface-placement.md is the one generated from the code.
// Usage: npx tsx scripts/design-brief-commands.ts          check
//        npx tsx scripts/design-brief-commands.ts --write  rewrite the table in docs/interface-placement.md
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { COMMAND_DEFINITIONS } from "../app/commands/registry";
import { COMMAND_GROUPS, commandTableProblems, keysLabel } from "../lib/editor/commands";

const root = path.join(__dirname, "..");
const read = (p: string) => readFileSync(path.join(root, p), "utf8").replace(/\r\n/g, "\n");
const problems: string[] = [...commandTableProblems(COMMAND_DEFINITIONS)];

// ---- 2. the brief's keys
const BRIEF = "docs/design-brief/04-editing.md";
const section = /## Keyboard shortcuts\n([\s\S]*?)\n## /.exec(read(BRIEF));
if (!section) problems.push(`${BRIEF} has no "Keyboard shortcuts" section.`);
const briefKeys = new Set<string>();
for (const line of (section?.[1] ?? "").split("\n")) {
  const cell = /^\| ([^|]+) \|/.exec(line)?.[1];
  if (!cell || cell === "Key" || /^-+$/.test(cell)) continue;
  for (const key of cell.split(",")) {
    briefKeys.add(
      key
        .replace(/\(held\)/, "")
        .replace(/Ctrl\/Cmd/, "Mod")
        .replace(/\s*\+\s*/g, "+")
        .trim()
    );
  }
}
const tableKeys = new Set(COMMAND_DEFINITIONS.flatMap((command) => [...(command.keys ?? [])]));
for (const key of tableKeys) if (!briefKeys.has(key)) problems.push(`The key "${key}" is in the command table and not in ${BRIEF}.`);
for (const key of briefKeys) if (!tableKeys.has(key)) problems.push(`The key "${key}" is in ${BRIEF} and no command has it.`);

// ---- 3. the generated table
const PLACEMENT = "docs/interface-placement.md";
const BEGIN = "<!-- commands:begin (generated by scripts/design-brief-commands.ts --write) -->";
const END = "<!-- commands:end -->";
const rows = COMMAND_GROUPS.flatMap((group) =>
  COMMAND_DEFINITIONS.filter((command) => command.group === group).map(
    (command, index) => `| ${index === 0 ? group : ""} | ${command.name} | ${keysLabel(command) || "—"} | ${command.when} |`
  )
);
const generated = [BEGIN, "| Group | Command | Key | Available when |", "|---|---|---|---|", ...rows, END].join("\n");
const placement = read(PLACEMENT);
const from = placement.indexOf(BEGIN);
const to = placement.indexOf(END);
if (from < 0 || to < 0) {
  problems.push(`${PLACEMENT} has no generated command table (the markers are missing).`);
} else if (process.argv.includes("--write")) {
  writeFileSync(path.join(root, PLACEMENT), placement.slice(0, from) + generated + placement.slice(to + END.length));
  console.log(`${PLACEMENT}: command table written (${COMMAND_DEFINITIONS.length} commands).`);
} else if (placement.slice(from, to + END.length) !== generated) {
  problems.push(`The command table in ${PLACEMENT} is not the one in code. Run: npx tsx scripts/design-brief-commands.ts --write`);
}

for (const problem of problems) console.log(problem);
console.log(problems.length === 0 ? `ok: ${COMMAND_DEFINITIONS.length} commands, ${tableKeys.size} keys` : `${problems.length} problem(s)`);
process.exit(problems.length === 0 ? 0 : 1);
