// Generated by `npm run dither-patterns` from `PATTERNS` in rust/cs-core/src/dither/mod.rs (G-100, D328).
// Do not edit by hand: CI regenerates it and fails if it differs.

/** The chooser's groups, in order, with the line each shows under its patterns' names. */
export const DITHER_GROUPS = [
  { id: "screens", label: "Screens — fewest single stitches" },
  { id: "scattered", label: "Scattered — closer to the photo" },
  { id: "diffusion", label: "Error diffusion — closest, never worse" },
  { id: "drawn", label: "Drawn — marks, not a pattern" },
] as const;

/** Choices several patterns share, each offered once with a variant chosen beneath the chooser. */
export const DITHER_CHOICES = [
  { id: "lines", label: "Lines", picturedBy: "lines-diagonal" },
] as const;

/** Every pattern, in the order the chooser shows them. `settings` is null for a pattern whose picture is built. */
export const DITHER_PATTERNS = [
  { id: "clustered-8", label: "Clustered dots", group: "screens", variant: null, settings: null },
  { id: "ring-8", label: "Rings", group: "screens", variant: null, settings: null },
  { id: "lines-horizontal", label: "Lines", group: "screens", variant: { choice: "lines", label: "—", title: "Horizontal lines" }, settings: null },
  { id: "lines-vertical", label: "Lines", group: "screens", variant: { choice: "lines", label: "|", title: "Vertical lines" }, settings: null },
  { id: "lines-diagonal", label: "Lines", group: "screens", variant: { choice: "lines", label: "/", title: "Diagonal lines, rising" }, settings: null },
  { id: "lines-anti-diagonal", label: "Lines", group: "screens", variant: { choice: "lines", label: "\\", title: "Diagonal lines, falling" }, settings: null },
  { id: "bayer-4", label: "Bayer 4×4", group: "scattered", variant: null, settings: null },
  { id: "bayer-8", label: "Bayer 8×8", group: "scattered", variant: null, settings: null },
  { id: "blue-noise-16", label: "Blue noise", group: "scattered", variant: null, settings: null },
  { id: "floyd-steinberg", label: "Floyd–Steinberg", group: "diffusion", variant: null, settings: null },
  { id: "atkinson", label: "Atkinson", group: "diffusion", variant: null, settings: null },
  { id: "hand-drawn", label: "Hand-drawn", group: "drawn", variant: null, settings: { key: "ditherTexture", control: "texture" } },
] as const;
